coupe/urls.py
from django.urls import path
from coupe import views

urlpatterns = [
    path('', views.coupe, name='coupe'),
]

scores/urls.py
from django.urls import path
from scores import views

urlpatterns = [
    path('', views.index, name='index'),
    path('fixtures/', views.fixtures, name='fixtures'),
    path('classement/', views.classement, name='classement'),
    path('fixture_detail/<int:id>/', views.fixture_detail, name='fixture_detail'),
    path('buteurs/', views.clsbuteurs, name='clsbuteurs'),
    path('cartons/', views.cards, name='cards'),
    path('addMessage/', views.addMessage, name='addMessage'),
    path('addgoalscorers/', views.goalscorers, name='goalscorers'),
]

zonefoot/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scores.urls')),
    path('coupe/', include('coupe.urls')),
    path('account/', include('account.urls')),
] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "LE PROFESSEUR"
admin.site.site_title = "ZONEFOOT6"
admin.site.index_title = "ZONEFOOT6"

scores/models.py
from django.db import models
from django.contrib.auth.models import User



TYPE_CARTON = (
    ('ROUGE', 'ROUGE'),
    ('JAUNE', 'JAUNE'),
)



class Team(models.Model):
    name = models.CharField(max_length=128, unique=True)
    affiliation = models.BooleanField(default=True)
    #mj = models.PositiveIntegerField(default=0)
    #gagne = models.PositiveIntegerField(default=0)
    #nul = models.PositiveIntegerField(default=0)
    #perdu = models.PositiveIntegerField(default=0)
    #bp = models.PositiveIntegerField(default=0)
    #bc = models.PositiveIntegerField(default=0)
    #points = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @property
    def mj(self):
    	nb_away = self.away_games.filter(game_finished=True).count()
    	nb_home = self.home_games.filter(game_finished=True).count()
    	return nb_home + nb_away


    @property
    def gagne(self):
    	win_away = 0
    	win_home = 0

    	for m in self.away_games.filter(game_finished=True):
    		if m.away_goals > m.home_goals:
    			win_away +=1
    	for m in self.home_games.filter(game_finished=True):
    		if m.home_goals > m.away_goals:
    			win_home +=1
    	return win_home + win_away

    @property
    def perdu(self):
    	lost_away = 0
    	lost_home = 0

    	for m in self.away_games.filter(game_finished=True):
    		if m.away_goals < m.home_goals:
    			lost_away +=1
    	for m in self.home_games.filter(game_finished=True):
    		if m.home_goals < m.away_goals:
    			lost_home +=1
    	return lost_home + lost_away

    @property
    def nul(self):
    	nul_away = 0
    	nul_home = 0

    	for m in self.away_games.filter(game_finished=True):
    		if m.home_goals == m.away_goals:
    			nul_away +=1
    	for m in self.home_games.filter(game_finished=True):
    		if m.away_goals == m.home_goals:
    			nul_home +=1
    	return nul_home + nul_away


    @property
    def points(self):
    	return self.gagne*3 + self.nul


    @property
    def bp(self):
    	bp_away = 0
    	bp_home = 0

    	for m in self.home_games.filter(game_finished=True):
    		bp_home += m.home_goals
    	for m in self.away_games.filter(game_finished=True):
    		bp_away += m.away_goals
    	return bp_away + bp_home

    @property
    def bc(self):
    	bc_away = 0
    	bc_home = 0

    	for m in self.home_games.filter(game_finished=True):
    		bc_home += m.away_goals
    	for m in self.away_games.filter(game_finished=True):
    		bc_away += m.home_goals
    	return bc_away + bc_home


    @property
    def db(self):
    	return self.bp - self.bc


   




class Fixture(models.Model):
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home_games')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away_games')
    home_goals = models.PositiveSmallIntegerField(default=0)
    away_goals = models.PositiveSmallIntegerField(default=0)
    game_finished = models.BooleanField(default=False)
    date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.home_team} vs {self.away_team}"





class Player(models.Model):
    name = models.CharField(max_length=128, unique=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    affiliation = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + "(" + self.team.name + ")"

    @property
    def totalbut(self):
        return But.objects.filter(player_id=self.id).count()





class But(models.Model):
    match = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    minute = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.player.name + " marque à la " + str(self.minute) + " minute"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    match = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    text = models.TextField()
    #parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + " ---Message---> " + self.text[:15]




class Carton(models.Model):
    match = models.ForeignKey(Fixture, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    date = models.DateTimeField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    type_carton = models.CharField(choices=TYPE_CARTON, max_length=7)
    paye = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.player.name + " carton: " + self.type_carton





class Info(models.Model):
    info = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.info

scores/forms.py
from django import forms
from .models import *
from django.forms import ModelForm, TextInput, Textarea, NumberInput

class DateInput(forms.DateInput):
    input_type = 'date'




#Buteurs
class ButForm(forms.ModelForm):
    class Meta:
        model = But
        fields = ('match', 'player', 'minute',)
        
        labels = {
            "match": "Match",
            "player": "Joueur",
            "minute": "Minute",
        }

scores/views.py
from django.shortcuts import render,  redirect, get_object_or_404
from .models import *
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
#from django.contrib.auth.forms import UserCreationForm
from django.contrib.admin.views.decorators import staff_member_required
from .forms import *



# Create your views here.
def index(request):
    fixtures = Fixture.objects.all().order_by('-date')

    context = {"fixtures": fixtures}
    return render(request, 'index.html', context)


def fixtures(request):
    fixtures = Fixture.objects.all().order_by('-date')

    #all_completed = all(f.game_finished for f in fixtures)

    context = {
        'fixtures': fixtures,
        #'all_completed': all_completed
    }

    
    return render(request, 'fixtures.html', context)




def classement(request):
    matchs = Fixture.objects.filter(game_finished=True)
    teams = sorted(Team.objects.all(), key=lambda t: (-t.points, -t.db)) #.order_by('-points')
    nb_matchs = matchs.count()
    context = {'nb_matchs': nb_matchs, 'teams': teams}
    return render(request, 'classement.html', context)





def clsbuteurs(request):
    buteurs = sorted(Player.objects.all(), key=lambda t: -t.totalbut)

    context={'buteurs': buteurs}

    return render(request, 'buteurs.html', context)




@login_required
def fixture_detail(request, id):
    fixture = get_object_or_404(Fixture, pk=id)

    home_team = fixture.home_team
    away_team = fixture.away_team

    home_team_buts = But.objects.filter(match = fixture, player__team = home_team)

    away_team_buts = But.objects.filter(match = fixture, player__team = away_team)

    #cartons = Carton.objects.filter(match = fixture)
    home_team_cartons = Carton.objects.filter(match = fixture, player__team = home_team)

    away_team_cartons = Carton.objects.filter(match = fixture, player__team = away_team)

    comments = Comment.objects.filter(match = fixture).order_by('-created_at')
    paginator = Paginator(comments, 20)
    page = request.GET.get('page', 1)
    comments = paginator.get_page(page)

    context={'home_team_buts': home_team_buts, 'away_team_buts': away_team_buts, 'away_team_cartons': away_team_cartons, 
    'home_team_cartons':home_team_cartons, 'fixture': fixture, 'comments': comments}

    return render(request, 'fixture_detail.html', context)


def addMessage(request):
    if request.method=="POST":
        comment=request.POST['comment']
        fixture_id=request.POST['fixtureid']
        fixture = get_object_or_404(Fixture, pk=fixture_id)
        
        newMessage = Comment(text=comment, user=request.user, match=fixture)
        newMessage.save()
        messages.success(request, 'Merci pour votre commentaire !!!')
        return redirect('fixture_detail', id=fixture_id)



def cards(request):
    cartons = Carton.objects.all()
    context = {'cartons': cartons}
    return render(request, 'cartons.html', context)




@login_required
def goalscorers(request):
    context = {}
    if request.method == "POST":
        form = ButForm(request.POST)
        if form.is_valid():
            scorer = form.cleaned_data['player']
            minute = form.cleaned_data['minute']
            form.instance.author = request.user
            form.save()
            messages.info(request, f'But à la {minute}ème minute de {scorer.name}!!!')
            return redirect('goalscorers')
    else:
        form = ButForm()

    context['form'] = form
    return render(request, 'goalscorersadd.html', context) 

scores/templates/base.html
<!-- parent template for about.html and home.html -->
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'ballon.jpg' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	{% if title %}
		<title>Zone-Foot - {{ title }}</title>
	{% else %}
		<title>ZoneFoot6</title>
	{% endif %}
</head>

<body>
	<!-- ================== nav bar ================== -->
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-success fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'index' %}">ZONEFOOT6</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'coupe' %}">Coupe</a>
	          <a class="nav-item nav-link" href="{% url 'fixtures' %}">Scores</a>
	          <a class="nav-item nav-link" href="{% url 'classement' %}">Classement</a>
	          <a class="nav-item nav-link" href="{% url 'clsbuteurs' %}">Buteurs</a>
	          <a class="nav-item nav-link" href="{% url 'cards' %}">Cartons</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	             {% if user.is_authenticated %}
				<a class="nav-item nav-link" href="{% url 'profile' %}">{{ request.user.username }}</a>
				<a class="nav-item nav-link" href="{% url 'logout' %}">LogOut</a>
			  {% else %}	
				<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
				<a class="nav-item nav-link" href="{% url 'inscription' %}">Register</a>
			  {% endif %}
			  
			 {% if user.is_staff %}
			  <a class="nav-item nav-link" href="/admin/" target="_blank">
				  <i class="fa fa-user-circle" aria-hidden="true"></i></a>
				{% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<!-- ================== Content block ================== -->
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
	      {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>Info Choc 💥.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">
	            	<p>{{ info }}</p>
	            </li>
	            <li class="list-group-item list-group-item-light">
	            	<a href="{% url 'goalscorers' %}">Add Goalscorers</a>
	            </li>
	            <li class="list-group-item list-group-item-light">Cartons</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>

	  <br>
	  <br>
	  <br>
	  <br>
	
	</main>

<section class="">
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: #1A8507;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">6ème Edition Zone Foot. TEL: 694 88 51 34 </span>
          <!--
          <button type="button" class="btn btn-outline-light">
            Sign up!
          </button>
      -->
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
       
      <a class="text-white" href="#">© 2022 Queen Love </a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>


	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
    $(document).ready(function() {
    $('#id_player').select2();
    $('#id_match').select2();
		});
		</script>

		<style type="text/css">
			#id_player{
				width: 100%;
			}
			#id_match{
				width: 100%;
			}
		</style>
</body>
</html>

scores/templates/base2.html
<!-- parent template for about.html and home.html -->
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'ballon.jpg' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	{% if title %}
		<title>Zone-Foot - {{ title }}</title>
	{% else %}
		<title>ZoneFoot6</title>
	{% endif %}
</head>

<body>
	<!-- ================== nav bar ================== -->
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-success fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{% url 'index' %}">ZONEFOOT6</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{% url 'coupe' %}">Coupe</a>
	          <a class="nav-item nav-link" href="{% url 'fixtures' %}">Scores</a>
	          <a class="nav-item nav-link" href="{% url 'classement' %}">Classement</a>
	          <a class="nav-item nav-link" href="{% url 'clsbuteurs' %}">Buteurs</a>
	          <a class="nav-item nav-link" href="{% url 'cards' %}">Cartons</a>
	        </div>
	        <!-- Navbar Right Side -->
	        <div class="navbar-nav">
	              {% if user.is_authenticated %}
				<a class="nav-item nav-link" href="{% url 'profile' %}">{{ request.user.username }}</a>
				<a class="nav-item nav-link" href="{% url 'logout' %}">LogOut</a>
			  {% else %}	
				<a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
				<a class="nav-item nav-link" href="{% url 'inscription' %}">Register</a>
			  {% endif %}
			  {% if user.is_staff %}
			  <a class="nav-item nav-link" href="/admin/" target="_blank">
				  <i class="fa fa-user-circle" aria-hidden="true"></i></a>
				{% endif %}
			
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>

	<!-- ================== Content block ================== -->
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-12">
	    	{% if messages %}
				{% for message in messages %}
					<div class="alert alert-{{ message.tags }}">
						{{ message }}
					</div>
				{% endfor %}
			{% endif %}
	      {% block content %}{% endblock %}
	    </div>
	    
	  </div>
	  <br>
	  <br>
	  <br>
	  <br>
	</main>

<section class="">
  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: #1A8507;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">6ème Edition Zone Foot. TEL: 694 88 51 34 </span>
          <!--
          <button type="button" class="btn btn-outline-light">
            Sign up!
          </button>
      -->
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
       
      <a class="text-white" href="#">© 2022 Queen Love </a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

scores/templates/buteurs.html
{% extends 'base.html' %} 

{% block content %}
<main>
    <h2>Classement de meilleurs buteurs</h2>

    <div class="input-group my-4">
        <input type="text"
               id="search-input", onkeyup="myFunction()", 
               class="form-control" 
               placeholder="Enter team" />

        <span class="input-group-text border-0 bg-transparent"  
              style="cursor: pointer;">
            <i class="fa fa-search" aria-hidden="true"></i>
        </span>
    </div>


<div class="container">
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"># Joueurs</th>
      <th scope="col">Equipe</th>
      <th scope="col">Total but(s)</th>
    </tr>
  </thead>
  <tbody>
    {% for b in buteurs %}
  
    <tr class="professeur">
      <td><span style="color: blue;">{{ forloop.counter }} ></span> {{ b.name }}</td>
      <td>{{ b.team.name }}</td>
      <td>{{ b.totalbut }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>




</main>
<script>
function myFunction() {
  // Declare variables
  var input, filter, rencontres, data, player, match, team, i;
  input = document.getElementById('search-input');
  filter = input.value.toUpperCase();
  rencontres = document.getElementsByClassName("professeur");

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < rencontres.length; i++) {
    data = rencontres[i].getElementsByTagName("td");
    player = data[0].textContent || data[0].innerText;
    team = data[1].textContent || data[1].innerText;

    if ((player.toUpperCase().indexOf(filter) > -1) || (team.toUpperCase().indexOf(filter) > -1))  {
      rencontres[i].style.display = "";
    } else {
      rencontres[i].style.display = "none";
    }
  }
}
</script>
{% endblock %}

scores/templates/cartons.html
{% extends 'base.html' %} 

{% block content %}
<main>
    <h2>Liste des sanctions</h2>

    <div class="input-group my-4">
        <input type="text"
               id="search-input", onkeyup="myFunction()", 
               class="form-control" 
               placeholder="Enter team" />

        <span class="input-group-text border-0 bg-transparent"  
              style="cursor: pointer;">
            <i class="fa fa-search" aria-hidden="true"></i>
        </span>
    </div>


<div class="container">
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"># Joueurs</th>
      <th scope="col">Equipe</th>
      <th scope="col">Match</th>
      <th scope="col">Carton</th>
      <th scope="col">Payé</th>
    </tr>
  </thead>
  <tbody>
    {% for c in cartons %}
  
    <tr class="professeur">
      <td><span style="color: blue;">{{ forloop.counter }} ></span> {{ c.player.name }}</td>
      <td>{{ c.player.team }}</td>
      <td>{{ c.match }}</td>
      <td>
          {% if c.type_carton == 'JAUNE' %}
          <span class="badge badge-warning">J</span>
          {% else %}
          <span class="badge badge-danger">R</span>
          {% endif %}
      </td>
      <td>{{ c.paye }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>




</main>

<script>
function myFunction() {
  // Declare variables
  var input, filter, rencontres, data, player, match, team, paye, i;
  input = document.getElementById('search-input');
  filter = input.value.toUpperCase();
  rencontres = document.getElementsByClassName("professeur");

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < rencontres.length; i++) {
    data = rencontres[i].getElementsByTagName("td");
    player = data[0].textContent || data[0].innerText;
    team = data[1].textContent || data[1].innerText;

    match = data[2].textContent || data[2].innerText;

    paye = data[4].textContent || data[4].innerText;

    if ((player.toUpperCase().indexOf(filter) > -1) || (team.toUpperCase().indexOf(filter) > -1) || (match.toUpperCase().indexOf(filter) > -1) || (paye.toUpperCase().indexOf(filter) > -1))  {
      rencontres[i].style.display = "";
    } else {
      rencontres[i].style.display = "none";
    }
  }
}
</script>
{% endblock %}

scores/templates/goalscorersadd.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
        <form action="" method="POST">{% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Ajouter un but</legend>
                {{ form|crispy }}
            </fieldset>

            {% if user.is_staff %}
            <button class="btn btn-success mt-3 mb-3" type="submit" style="float: right;">
                <i class="fas fa-database"></i> Ajouter le but
            </button>
            {% else %}
            <p style="font-style: italic; color: brown;">Vous devez être un staff pour faire des ajouts !!!</p>
            {% endif %}
        </form>       
    </div>
{% endblock content %}